let connections = {}; // socket connection generated by each client request
let clients = {}; // stores only userId and userName used in the context of a websocket

const getConnections = () => connections;
const addConnection = (key, connection) => (connections[key] = connection);
const deleteConnection = (userId) => {
  delete connections[userId];
};

const getClients = () => {
  return clients;
};

const addClient = (userId, username) => {
  clients[userId] = { userId, username };
};

const deleteClient = (userId) => {
  delete clients[userId];
};

const ws = {
  getConnections,
  addConnection,
  deleteConnection,
  getClients,
  addClient,
  deleteClient,
};

module.exports = { ws };
